export const DATA_REQUEST: "DATA_REQUEST" = "DATA_REQUEST";
export const DATA_SUCCESS: "DATA_SUCCESS" = "DATA_SUCCESS";
export const DATA_ERROR: "DATA_ERROR" = "DATA_ERROR";

export const REMOVE_ITEM: "REMOVE_ITEM" = "REMOVE_ITEM";
